export const COMBATANS = [
    { "value": "amir", "label": "Amir" },
    { "value": "beryl", "label": "Beryl" },
    { "value": "cassius", "label": "Cassius" },
    { "value": "chizuru", "label": "Chizuru" },
    { "value": "haru", "label": "Haru" },
    { "value": "hugo", "label": "Hugo" },
    { "value": "kayron", "label": "Kayron" },
    { "value": "khalipe", "label": "Khalipe" },
    { "value": "lucas", "label": "Lucas" },
    { "value": "luke", "label": "Luke" },
    { "value": "magna", "label": "Magna" },
    { "value": "maribell", "label": "Maribell" },
    { "value": "mei_lin", "label": "Mei Lin" },
    { "value": "mika", "label": "Mika" },
    { "value": "narja", "label": "Narja" },
    { "value": "nia", "label": "Nia" },
    { "value": "orlea", "label": "Orlea" },
    { "value": "owen", "label": "Owen" },
    { "value": "rei", "label": "Rei" },
    { "value": "renoa", "label": "Renoa" },
    { "value": "rin", "label": "Rin" },
    { "value": "selena", "label": "Selena" },
    { "value": "sereniel", "label": "Sereniel" },
    { "value": "tressa", "label": "Tressa" },
    { "value": "veronica", "label": "Veronica" },
    { "value": "yuki", "label": "Yuki" }
]

export const COMBATANS_ENUMS = [
    "amir",
    "beryl",
    "cassius",
    "chizuru",
    "haru",
    "hugo",
    "kayron",
    "khalipe",
    "lucas",
    "luke",
    "magna",
    "maribell",
    "mei_lin",
    "mika",
    "narja",
    "nia",
    "orlea",
    "owen",
    "rei",
    "renoa",
    "rin",
    "selena",
    "sereniel",
    "tressa",
    "veronica",
    "yuki"
]