/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MostFavoritedRouteImport } from './routes/most-favorited'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as StaticRouteRouteImport } from './routes/_static/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedDataIdRouteImport } from './routes/saved-data.$id'
import { Route as StaticDocsIndexRouteImport } from './routes/_static/docs/index'
import { Route as ApiUserDetailsUserIdRouteImport } from './routes/api/user-details.$userId'
import { Route as ApiSavedDataIdRouteImport } from './routes/api/saved-data.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as StaticDocsNameRouteImport } from './routes/_static/docs/$name'
import { Route as AuthAppPostRouteImport } from './routes/_auth/app/post'
import { Route as AuthAppNameRouteImport } from './routes/_auth/app/name'
import { Route as UserUserIdPageSizeRouteImport } from './routes/user.$userId.$page.$size'
import { Route as ApiPaginatedSavedDataPageSizeRouteImport } from './routes/api/paginated-saved-data.$page.$size'
import { Route as ApiMostFavoritedPageSizeRouteImport } from './routes/api/most-favorited.$page.$size'
import { Route as ApiBookmarkUserIdSavedDataIdRouteImport } from './routes/api/bookmark.$userId.$savedDataId'
import { Route as AuthAppPolarSubscriptionsRouteImport } from './routes/_auth/app/polar/subscriptions'
import { Route as AuthAppPolarPortalRouteImport } from './routes/_auth/app/polar/portal'
import { Route as AuthAppEditIdRouteImport } from './routes/_auth/app/edit.$id'
import { Route as ApiProtectedUserSavedDataPageSizeRouteImport } from './routes/api/protected/user-saved-data.$page.$size'
import { Route as ApiProtectedUserFavoritedPageSizeRouteImport } from './routes/api/protected/user-favorited.$page.$size'
import { Route as AuthAppPolarCheckoutSuccessRouteImport } from './routes/_auth/app/polar/checkout.success'
import { Route as AuthAppMySavedDataUserIdPagePageSizeRouteImport } from './routes/_auth/app/my-saved-data.$userId.$page.$pageSize'
import { Route as AuthAppMyFavoritedUserIdPagePageSizeRouteImport } from './routes/_auth/app/my-favorited.$userId.$page.$pageSize'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MostFavoritedRoute = MostFavoritedRouteImport.update({
  id: '/most-favorited',
  path: '/most-favorited',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticRouteRoute = StaticRouteRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedDataIdRoute = SavedDataIdRouteImport.update({
  id: '/saved-data/$id',
  path: '/saved-data/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticDocsIndexRoute = StaticDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => StaticRouteRoute,
} as any)
const ApiUserDetailsUserIdRoute = ApiUserDetailsUserIdRouteImport.update({
  id: '/api/user-details/$userId',
  path: '/api/user-details/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedDataIdRoute = ApiSavedDataIdRouteImport.update({
  id: '/api/saved-data/$id',
  path: '/api/saved-data/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticDocsNameRoute = StaticDocsNameRouteImport.update({
  id: '/docs/$name',
  path: '/docs/$name',
  getParentRoute: () => StaticRouteRoute,
} as any)
const AuthAppPostRoute = AuthAppPostRouteImport.update({
  id: '/app/post',
  path: '/app/post',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppNameRoute = AuthAppNameRouteImport.update({
  id: '/app/name',
  path: '/app/name',
  getParentRoute: () => AuthRouteRoute,
} as any)
const UserUserIdPageSizeRoute = UserUserIdPageSizeRouteImport.update({
  id: '/user/$userId/$page/$size',
  path: '/user/$userId/$page/$size',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaginatedSavedDataPageSizeRoute =
  ApiPaginatedSavedDataPageSizeRouteImport.update({
    id: '/api/paginated-saved-data/$page/$size',
    path: '/api/paginated-saved-data/$page/$size',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMostFavoritedPageSizeRoute =
  ApiMostFavoritedPageSizeRouteImport.update({
    id: '/api/most-favorited/$page/$size',
    path: '/api/most-favorited/$page/$size',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookmarkUserIdSavedDataIdRoute =
  ApiBookmarkUserIdSavedDataIdRouteImport.update({
    id: '/api/bookmark/$userId/$savedDataId',
    path: '/api/bookmark/$userId/$savedDataId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAppPolarSubscriptionsRoute =
  AuthAppPolarSubscriptionsRouteImport.update({
    id: '/app/polar/subscriptions',
    path: '/app/polar/subscriptions',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarPortalRoute = AuthAppPolarPortalRouteImport.update({
  id: '/app/polar/portal',
  path: '/app/polar/portal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppEditIdRoute = AuthAppEditIdRouteImport.update({
  id: '/app/edit/$id',
  path: '/app/edit/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiProtectedUserSavedDataPageSizeRoute =
  ApiProtectedUserSavedDataPageSizeRouteImport.update({
    id: '/api/protected/user-saved-data/$page/$size',
    path: '/api/protected/user-saved-data/$page/$size',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtectedUserFavoritedPageSizeRoute =
  ApiProtectedUserFavoritedPageSizeRouteImport.update({
    id: '/api/protected/user-favorited/$page/$size',
    path: '/api/protected/user-favorited/$page/$size',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAppPolarCheckoutSuccessRoute =
  AuthAppPolarCheckoutSuccessRouteImport.update({
    id: '/app/polar/checkout/success',
    path: '/app/polar/checkout/success',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppMySavedDataUserIdPagePageSizeRoute =
  AuthAppMySavedDataUserIdPagePageSizeRouteImport.update({
    id: '/app/my-saved-data/$userId/$page/$pageSize',
    path: '/app/my-saved-data/$userId/$page/$pageSize',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppMyFavoritedUserIdPagePageSizeRoute =
  AuthAppMyFavoritedUserIdPagePageSizeRouteImport.update({
    id: '/app/my-favorited/$userId/$page/$pageSize',
    path: '/app/my-favorited/$userId/$page/$pageSize',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/contributors': typeof ContributorsRoute
  '/login': typeof LoginRoute
  '/most-favorited': typeof MostFavoritedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/saved-data/$id': typeof SavedDataIdRoute
  '/app/name': typeof AuthAppNameRoute
  '/app/post': typeof AuthAppPostRoute
  '/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/saved-data/$id': typeof ApiSavedDataIdRoute
  '/api/user-details/$userId': typeof ApiUserDetailsUserIdRoute
  '/docs': typeof StaticDocsIndexRoute
  '/app/edit/$id': typeof AuthAppEditIdRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/bookmark/$userId/$savedDataId': typeof ApiBookmarkUserIdSavedDataIdRoute
  '/api/most-favorited/$page/$size': typeof ApiMostFavoritedPageSizeRoute
  '/api/paginated-saved-data/$page/$size': typeof ApiPaginatedSavedDataPageSizeRoute
  '/user/$userId/$page/$size': typeof UserUserIdPageSizeRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
  '/api/protected/user-favorited/$page/$size': typeof ApiProtectedUserFavoritedPageSizeRoute
  '/api/protected/user-saved-data/$page/$size': typeof ApiProtectedUserSavedDataPageSizeRoute
  '/app/my-favorited/$userId/$page/$pageSize': typeof AuthAppMyFavoritedUserIdPagePageSizeRoute
  '/app/my-saved-data/$userId/$page/$pageSize': typeof AuthAppMySavedDataUserIdPagePageSizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/contributors': typeof ContributorsRoute
  '/login': typeof LoginRoute
  '/most-favorited': typeof MostFavoritedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/saved-data/$id': typeof SavedDataIdRoute
  '/app/name': typeof AuthAppNameRoute
  '/app/post': typeof AuthAppPostRoute
  '/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/saved-data/$id': typeof ApiSavedDataIdRoute
  '/api/user-details/$userId': typeof ApiUserDetailsUserIdRoute
  '/docs': typeof StaticDocsIndexRoute
  '/app/edit/$id': typeof AuthAppEditIdRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/bookmark/$userId/$savedDataId': typeof ApiBookmarkUserIdSavedDataIdRoute
  '/api/most-favorited/$page/$size': typeof ApiMostFavoritedPageSizeRoute
  '/api/paginated-saved-data/$page/$size': typeof ApiPaginatedSavedDataPageSizeRoute
  '/user/$userId/$page/$size': typeof UserUserIdPageSizeRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
  '/api/protected/user-favorited/$page/$size': typeof ApiProtectedUserFavoritedPageSizeRoute
  '/api/protected/user-saved-data/$page/$size': typeof ApiProtectedUserSavedDataPageSizeRoute
  '/app/my-favorited/$userId/$page/$pageSize': typeof AuthAppMyFavoritedUserIdPagePageSizeRoute
  '/app/my-saved-data/$userId/$page/$pageSize': typeof AuthAppMySavedDataUserIdPagePageSizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_static': typeof StaticRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/contributors': typeof ContributorsRoute
  '/login': typeof LoginRoute
  '/most-favorited': typeof MostFavoritedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/saved-data/$id': typeof SavedDataIdRoute
  '/_auth/app/name': typeof AuthAppNameRoute
  '/_auth/app/post': typeof AuthAppPostRoute
  '/_static/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/saved-data/$id': typeof ApiSavedDataIdRoute
  '/api/user-details/$userId': typeof ApiUserDetailsUserIdRoute
  '/_static/docs/': typeof StaticDocsIndexRoute
  '/_auth/app/edit/$id': typeof AuthAppEditIdRoute
  '/_auth/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/_auth/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/bookmark/$userId/$savedDataId': typeof ApiBookmarkUserIdSavedDataIdRoute
  '/api/most-favorited/$page/$size': typeof ApiMostFavoritedPageSizeRoute
  '/api/paginated-saved-data/$page/$size': typeof ApiPaginatedSavedDataPageSizeRoute
  '/user/$userId/$page/$size': typeof UserUserIdPageSizeRoute
  '/_auth/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
  '/api/protected/user-favorited/$page/$size': typeof ApiProtectedUserFavoritedPageSizeRoute
  '/api/protected/user-saved-data/$page/$size': typeof ApiProtectedUserSavedDataPageSizeRoute
  '/_auth/app/my-favorited/$userId/$page/$pageSize': typeof AuthAppMyFavoritedUserIdPagePageSizeRoute
  '/_auth/app/my-saved-data/$userId/$page/$pageSize': typeof AuthAppMySavedDataUserIdPagePageSizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/contributors'
    | '/login'
    | '/most-favorited'
    | '/privacy-policy'
    | '/tos'
    | '/saved-data/$id'
    | '/app/name'
    | '/app/post'
    | '/docs/$name'
    | '/api/auth/$'
    | '/api/saved-data/$id'
    | '/api/user-details/$userId'
    | '/docs'
    | '/app/edit/$id'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/api/bookmark/$userId/$savedDataId'
    | '/api/most-favorited/$page/$size'
    | '/api/paginated-saved-data/$page/$size'
    | '/user/$userId/$page/$size'
    | '/app/polar/checkout/success'
    | '/api/protected/user-favorited/$page/$size'
    | '/api/protected/user-saved-data/$page/$size'
    | '/app/my-favorited/$userId/$page/$pageSize'
    | '/app/my-saved-data/$userId/$page/$pageSize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/contributors'
    | '/login'
    | '/most-favorited'
    | '/privacy-policy'
    | '/tos'
    | '/saved-data/$id'
    | '/app/name'
    | '/app/post'
    | '/docs/$name'
    | '/api/auth/$'
    | '/api/saved-data/$id'
    | '/api/user-details/$userId'
    | '/docs'
    | '/app/edit/$id'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/api/bookmark/$userId/$savedDataId'
    | '/api/most-favorited/$page/$size'
    | '/api/paginated-saved-data/$page/$size'
    | '/user/$userId/$page/$size'
    | '/app/polar/checkout/success'
    | '/api/protected/user-favorited/$page/$size'
    | '/api/protected/user-saved-data/$page/$size'
    | '/app/my-favorited/$userId/$page/$pageSize'
    | '/app/my-saved-data/$userId/$page/$pageSize'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_static'
    | '/chat'
    | '/contributors'
    | '/login'
    | '/most-favorited'
    | '/privacy-policy'
    | '/tos'
    | '/saved-data/$id'
    | '/_auth/app/name'
    | '/_auth/app/post'
    | '/_static/docs/$name'
    | '/api/auth/$'
    | '/api/saved-data/$id'
    | '/api/user-details/$userId'
    | '/_static/docs/'
    | '/_auth/app/edit/$id'
    | '/_auth/app/polar/portal'
    | '/_auth/app/polar/subscriptions'
    | '/api/bookmark/$userId/$savedDataId'
    | '/api/most-favorited/$page/$size'
    | '/api/paginated-saved-data/$page/$size'
    | '/user/$userId/$page/$size'
    | '/_auth/app/polar/checkout/success'
    | '/api/protected/user-favorited/$page/$size'
    | '/api/protected/user-saved-data/$page/$size'
    | '/_auth/app/my-favorited/$userId/$page/$pageSize'
    | '/_auth/app/my-saved-data/$userId/$page/$pageSize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  StaticRouteRoute: typeof StaticRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  ContributorsRoute: typeof ContributorsRoute
  LoginRoute: typeof LoginRoute
  MostFavoritedRoute: typeof MostFavoritedRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TosRoute: typeof TosRoute
  SavedDataIdRoute: typeof SavedDataIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSavedDataIdRoute: typeof ApiSavedDataIdRoute
  ApiUserDetailsUserIdRoute: typeof ApiUserDetailsUserIdRoute
  ApiBookmarkUserIdSavedDataIdRoute: typeof ApiBookmarkUserIdSavedDataIdRoute
  ApiMostFavoritedPageSizeRoute: typeof ApiMostFavoritedPageSizeRoute
  ApiPaginatedSavedDataPageSizeRoute: typeof ApiPaginatedSavedDataPageSizeRoute
  UserUserIdPageSizeRoute: typeof UserUserIdPageSizeRoute
  ApiProtectedUserFavoritedPageSizeRoute: typeof ApiProtectedUserFavoritedPageSizeRoute
  ApiProtectedUserSavedDataPageSizeRoute: typeof ApiProtectedUserSavedDataPageSizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/most-favorited': {
      id: '/most-favorited'
      path: '/most-favorited'
      fullPath: '/most-favorited'
      preLoaderRoute: typeof MostFavoritedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-data/$id': {
      id: '/saved-data/$id'
      path: '/saved-data/$id'
      fullPath: '/saved-data/$id'
      preLoaderRoute: typeof SavedDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/docs/': {
      id: '/_static/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof StaticDocsIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/api/user-details/$userId': {
      id: '/api/user-details/$userId'
      path: '/api/user-details/$userId'
      fullPath: '/api/user-details/$userId'
      preLoaderRoute: typeof ApiUserDetailsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saved-data/$id': {
      id: '/api/saved-data/$id'
      path: '/api/saved-data/$id'
      fullPath: '/api/saved-data/$id'
      preLoaderRoute: typeof ApiSavedDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/docs/$name': {
      id: '/_static/docs/$name'
      path: '/docs/$name'
      fullPath: '/docs/$name'
      preLoaderRoute: typeof StaticDocsNameRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_auth/app/post': {
      id: '/_auth/app/post'
      path: '/app/post'
      fullPath: '/app/post'
      preLoaderRoute: typeof AuthAppPostRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/name': {
      id: '/_auth/app/name'
      path: '/app/name'
      fullPath: '/app/name'
      preLoaderRoute: typeof AuthAppNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/user/$userId/$page/$size': {
      id: '/user/$userId/$page/$size'
      path: '/user/$userId/$page/$size'
      fullPath: '/user/$userId/$page/$size'
      preLoaderRoute: typeof UserUserIdPageSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paginated-saved-data/$page/$size': {
      id: '/api/paginated-saved-data/$page/$size'
      path: '/api/paginated-saved-data/$page/$size'
      fullPath: '/api/paginated-saved-data/$page/$size'
      preLoaderRoute: typeof ApiPaginatedSavedDataPageSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/most-favorited/$page/$size': {
      id: '/api/most-favorited/$page/$size'
      path: '/api/most-favorited/$page/$size'
      fullPath: '/api/most-favorited/$page/$size'
      preLoaderRoute: typeof ApiMostFavoritedPageSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmark/$userId/$savedDataId': {
      id: '/api/bookmark/$userId/$savedDataId'
      path: '/api/bookmark/$userId/$savedDataId'
      fullPath: '/api/bookmark/$userId/$savedDataId'
      preLoaderRoute: typeof ApiBookmarkUserIdSavedDataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/polar/subscriptions': {
      id: '/_auth/app/polar/subscriptions'
      path: '/app/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/portal': {
      id: '/_auth/app/polar/portal'
      path: '/app/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthAppPolarPortalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/edit/$id': {
      id: '/_auth/app/edit/$id'
      path: '/app/edit/$id'
      fullPath: '/app/edit/$id'
      preLoaderRoute: typeof AuthAppEditIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/protected/user-saved-data/$page/$size': {
      id: '/api/protected/user-saved-data/$page/$size'
      path: '/api/protected/user-saved-data/$page/$size'
      fullPath: '/api/protected/user-saved-data/$page/$size'
      preLoaderRoute: typeof ApiProtectedUserSavedDataPageSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/user-favorited/$page/$size': {
      id: '/api/protected/user-favorited/$page/$size'
      path: '/api/protected/user-favorited/$page/$size'
      fullPath: '/api/protected/user-favorited/$page/$size'
      preLoaderRoute: typeof ApiProtectedUserFavoritedPageSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/polar/checkout/success': {
      id: '/_auth/app/polar/checkout/success'
      path: '/app/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/my-saved-data/$userId/$page/$pageSize': {
      id: '/_auth/app/my-saved-data/$userId/$page/$pageSize'
      path: '/app/my-saved-data/$userId/$page/$pageSize'
      fullPath: '/app/my-saved-data/$userId/$page/$pageSize'
      preLoaderRoute: typeof AuthAppMySavedDataUserIdPagePageSizeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/my-favorited/$userId/$page/$pageSize': {
      id: '/_auth/app/my-favorited/$userId/$page/$pageSize'
      path: '/app/my-favorited/$userId/$page/$pageSize'
      fullPath: '/app/my-favorited/$userId/$page/$pageSize'
      preLoaderRoute: typeof AuthAppMyFavoritedUserIdPagePageSizeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppNameRoute: typeof AuthAppNameRoute
  AuthAppPostRoute: typeof AuthAppPostRoute
  AuthAppEditIdRoute: typeof AuthAppEditIdRoute
  AuthAppPolarPortalRoute: typeof AuthAppPolarPortalRoute
  AuthAppPolarSubscriptionsRoute: typeof AuthAppPolarSubscriptionsRoute
  AuthAppPolarCheckoutSuccessRoute: typeof AuthAppPolarCheckoutSuccessRoute
  AuthAppMyFavoritedUserIdPagePageSizeRoute: typeof AuthAppMyFavoritedUserIdPagePageSizeRoute
  AuthAppMySavedDataUserIdPagePageSizeRoute: typeof AuthAppMySavedDataUserIdPagePageSizeRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppNameRoute: AuthAppNameRoute,
  AuthAppPostRoute: AuthAppPostRoute,
  AuthAppEditIdRoute: AuthAppEditIdRoute,
  AuthAppPolarPortalRoute: AuthAppPolarPortalRoute,
  AuthAppPolarSubscriptionsRoute: AuthAppPolarSubscriptionsRoute,
  AuthAppPolarCheckoutSuccessRoute: AuthAppPolarCheckoutSuccessRoute,
  AuthAppMyFavoritedUserIdPagePageSizeRoute:
    AuthAppMyFavoritedUserIdPagePageSizeRoute,
  AuthAppMySavedDataUserIdPagePageSizeRoute:
    AuthAppMySavedDataUserIdPagePageSizeRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface StaticRouteRouteChildren {
  StaticDocsNameRoute: typeof StaticDocsNameRoute
  StaticDocsIndexRoute: typeof StaticDocsIndexRoute
}

const StaticRouteRouteChildren: StaticRouteRouteChildren = {
  StaticDocsNameRoute: StaticDocsNameRoute,
  StaticDocsIndexRoute: StaticDocsIndexRoute,
}

const StaticRouteRouteWithChildren = StaticRouteRoute._addFileChildren(
  StaticRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  StaticRouteRoute: StaticRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  ContributorsRoute: ContributorsRoute,
  LoginRoute: LoginRoute,
  MostFavoritedRoute: MostFavoritedRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TosRoute: TosRoute,
  SavedDataIdRoute: SavedDataIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSavedDataIdRoute: ApiSavedDataIdRoute,
  ApiUserDetailsUserIdRoute: ApiUserDetailsUserIdRoute,
  ApiBookmarkUserIdSavedDataIdRoute: ApiBookmarkUserIdSavedDataIdRoute,
  ApiMostFavoritedPageSizeRoute: ApiMostFavoritedPageSizeRoute,
  ApiPaginatedSavedDataPageSizeRoute: ApiPaginatedSavedDataPageSizeRoute,
  UserUserIdPageSizeRoute: UserUserIdPageSizeRoute,
  ApiProtectedUserFavoritedPageSizeRoute:
    ApiProtectedUserFavoritedPageSizeRoute,
  ApiProtectedUserSavedDataPageSizeRoute:
    ApiProtectedUserSavedDataPageSizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
